services:
  - type: web
    name: academic-support-system
    env: python
    plan: free
    buildCommand: "./render-build.sh && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: SECRET_KEY
        value: your_secret_key  # Change this to your actual secret key or set it in the Render dashboard
      - key: MYSQL_HOST
        value: localhost  # Change this to your actual MySQL host
      - key: MYSQL_USER
        value:root   # Change thisroot to your actual MySQL user
      - key: MYSQL_PASSWORD
        value:  # Change this to your actual MySQL password
      - key: MYSQL_DB
        value: academic_support_system  # Change this to your actual MySQL database name
